version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1

  #
  #  kibana:
  #    image: 'docker.elastic.co/kibana/kibana:6.4.2'
  #    container_name: kibana
  #    environment:
  #      SERVER_NAME: kibana.local
  #      ELASTICSEARCH_URL: http://elasticsearch:9200
  #    ports:
  #      - '5601:5601'
  #
  #  headPlugin:
  #    image: 'mobz/elasticsearch-head:5'
  #    container_name: head
  #    ports:
  #      - '9100:9100'

  #  redis:
  #    image: redis:alpine
  #    container_name: redis_db
  #    command: redis-server --appendonly yes
  #    ports:
  #      - 6379:6379
  #    # volumes:
  #    #   - ./data:/data
  #    restart: always
  #  idp:
  #    depends_on:
  #      - redis
  #    image: rediscommander/redis-commander
  #    container_name: redis_comndr
  #    environment:
  #    - REDIS_HOSTS=local:redis:6379
  #    ports:
  #      - 8081:8081
  #    links:
  #      - redis:redis
  #    restart: always

  kafka:
    image: landoop/fast-data-dev:2.5.1
    ports:
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "2181:2181"
      - "3030:3030" # UI: http://localhost:3030/
      - "9581-9585:9581-9585"
    environment:
      - ADV_HOST=localhost # Use your 'docker-machine ip' or 'localhost' if linux

